package compiler

import (
	"fmt"
	"strings"
)

func GenerateRust(policy *Policy) (string, error) {
	var b strings.Builder

	b.WriteString(fmt.Sprintf("// Auto-generated by warmor-compile from: %s\n", policy.Name))
	b.WriteString("// DO NOT EDIT — regenerate from the source YAML policy.\n\n")
	b.WriteString("#![no_std]\n\n")
	b.WriteString("const ACTION_ALLOW: i32 = 0;\nconst ACTION_DENY: i32 = 1;\nconst ACTION_LOG: i32 = 2;\nconst ACTION_AUDIT_DENY: i32 = 3;\n\n")

	// Event type constants matching Go's binary layout
	b.WriteString("const EVENT_PROCESS: u8 = 0;\nconst EVENT_FILE: u8 = 1;\nconst EVENT_NETWORK: u8 = 2;\n\n")

	// Binary struct field offsets
	writeBinaryOffsets(&b)
	writeHelperFunctions(&b)
	writeMallocFree(&b)
	writeReasonTable(&b, policy)
	writeEvaluateEventFunction(&b, policy)
	writeGetLastMatchedRule(&b)

	// Host callback extern declarations
	writeHostExterns(&b)

	return b.String(), nil
}

func writeBinaryOffsets(b *strings.Builder) {
	b.WriteString(`// Binary event struct layout (256 bytes, LE)
const OFF_PID: usize = 0;
const OFF_UID: usize = 4;
const OFF_GID: usize = 8;
const OFF_EVENT_TYPE: usize = 12;
const OFF_COMM: usize = 13;
const OFF_COMM_LEN: usize = 64;
const OFF_PRIMARY_STR: usize = 77;
const OFF_PRIMARY_STR_LEN: usize = 128;
const OFF_FLAGS: usize = 205;
const OFF_REMOTE_PORT: usize = 209;
const OFF_LOCAL_PORT: usize = 211;
const OFF_SECONDARY_STR: usize = 213;
const OFF_SECONDARY_STR_LEN: usize = 32;

`)
}

func writeHelperFunctions(b *strings.Builder) {
	b.WriteString(`unsafe fn read_u32(base: *const u8, offset: usize) -> u32 {
    let p = base.add(offset);
    ((*p) as u32)
        | ((*p.add(1)) as u32) << 8
        | ((*p.add(2)) as u32) << 16
        | ((*p.add(3)) as u32) << 24
}

unsafe fn read_u16(base: *const u8, offset: usize) -> u16 {
    let p = base.add(offset);
    ((*p) as u16) | ((*p.add(1)) as u16) << 8
}

unsafe fn read_str<'a>(base: *const u8, offset: usize, max_len: usize) -> &'a str {
    let p = base.add(offset);
    let mut len = 0;
    while len < max_len && *p.add(len) != 0 {
        len += 1;
    }
    let slice = core::slice::from_raw_parts(p, len);
    core::str::from_utf8_unchecked(slice)
}

fn matches_glob(s: &str, pattern: &str) -> bool {
    glob_match(s.as_bytes(), pattern.as_bytes())
}

fn glob_match(s: &[u8], p: &[u8]) -> bool {
    let mut si = 0;
    let mut pi = 0;
    let mut star_pi = usize::MAX;
    let mut star_si = 0;

    while si < s.len() {
        if pi < p.len() && p[pi] == b'*' {
            if pi + 1 < p.len() && p[pi + 1] == b'*' {
                pi += 2;
                if pi < p.len() && p[pi] == b'/' {
                    pi += 1;
                }
                star_pi = pi;
                star_si = si;
            } else {
                pi += 1;
                star_pi = pi;
                star_si = si;
            }
        } else if pi < p.len() && (p[pi] == b'?' || p[pi] == s[si]) {
            si += 1;
            pi += 1;
        } else if star_pi != usize::MAX {
            pi = star_pi;
            star_si += 1;
            si = star_si;
        } else {
            return false;
        }
    }

    while pi < p.len() && p[pi] == b'*' {
        pi += 1;
    }

    pi == p.len()
}

fn any_of_str(s: &str, values: &[&str]) -> bool {
    let mut i = 0;
    while i < values.len() {
        if values[i] == s {
            return true;
        }
        i += 1;
    }
    false
}

fn none_of_str(s: &str, values: &[&str]) -> bool {
    !any_of_str(s, values)
}

fn any_of_u32(val: u32, values: &[u32]) -> bool {
    let mut i = 0;
    while i < values.len() {
        if values[i] == val {
            return true;
        }
        i += 1;
    }
    false
}

fn none_of_u32(val: u32, values: &[u32]) -> bool {
    !any_of_u32(val, values)
}

fn any_of_u16(val: u16, values: &[u16]) -> bool {
    let mut i = 0;
    while i < values.len() {
        if values[i] == val {
            return true;
        }
        i += 1;
    }
    false
}

fn none_of_u16(val: u16, values: &[u16]) -> bool {
    !any_of_u16(val, values)
}

fn str_starts_with(s: &str, prefix: &str) -> bool {
    s.as_bytes().len() >= prefix.as_bytes().len()
        && &s.as_bytes()[..prefix.as_bytes().len()] == prefix.as_bytes()
}

fn str_contains(s: &str, needle: &str) -> bool {
    if needle.is_empty() {
        return true;
    }
    let sb = s.as_bytes();
    let nb = needle.as_bytes();
    if nb.len() > sb.len() {
        return false;
    }
    let mut i = 0;
    while i <= sb.len() - nb.len() {
        if &sb[i..i + nb.len()] == nb {
            return true;
        }
        i += 1;
    }
    false
}

`)
}

func writeMallocFree(b *strings.Builder) {
	b.WriteString(`#[no_mangle]
pub extern "C" fn malloc(size: usize) -> *mut u8 {
    let layout = unsafe { core::alloc::Layout::from_size_align_unchecked(size, 1) };
    unsafe { ALLOCATOR.alloc(layout) }
}

#[no_mangle]
pub extern "C" fn free(ptr: *mut u8, size: usize) {
    let layout = unsafe { core::alloc::Layout::from_size_align_unchecked(size, 1) };
    unsafe { ALLOCATOR.dealloc(ptr, layout) }
}

// Simple bump allocator for no_std
use core::alloc::{GlobalAlloc, Layout};

struct BumpAllocator;

unsafe impl GlobalAlloc for BumpAllocator {
    unsafe fn alloc(&self, layout: Layout) -> *mut u8 {
        let size = layout.size();
        let align = layout.align();
        let mask = align - 1;
        let current = HEAP_POS;
        let aligned = (current + mask) & !mask;
        let new_pos = aligned + size;
        if new_pos > HEAP.len() {
            return core::ptr::null_mut();
        }
        HEAP_POS = new_pos;
        HEAP.as_mut_ptr().add(aligned)
    }

    unsafe fn dealloc(&self, _ptr: *mut u8, _layout: Layout) {}
}

#[global_allocator]
static ALLOCATOR: BumpAllocator = BumpAllocator;

static mut HEAP: [u8; 65536] = [0u8; 65536];
static mut HEAP_POS: usize = 0;

#[panic_handler]
fn panic(_info: &core::panic::PanicInfo) -> ! {
    loop {}
}

`)
}

func writeReasonTable(b *strings.Builder, policy *Policy) {
	b.WriteString("static RULE_REASONS: &[&str] = &[\n")
	for _, rule := range policy.Rules {
		reason := rule.Reason
		if reason == "" {
			reason = fmt.Sprintf("Rule: %s", rule.Name)
		}
		b.WriteString(fmt.Sprintf("    %q,\n", reason))
	}
	b.WriteString("];\n\n")
	b.WriteString("static mut LAST_MATCHED: u32 = 0xFFFFFFFF;\n\n")
}

func writeEvaluateEventFunction(b *strings.Builder, policy *Policy) {
	b.WriteString(`#[no_mangle]
pub extern "C" fn evaluate_event(offset: u32) -> i32 {
    unsafe {
        let base = offset as *const u8;
        let event_type = *base.add(OFF_EVENT_TYPE);
        LAST_MATCHED = 0xFFFFFFFF;
        match event_type {
            EVENT_PROCESS => evaluate_process(base),
            EVENT_FILE => evaluate_file(base),
            EVENT_NETWORK => evaluate_network(base),
            _ => ACTION_DENY,
        }
    }
}

`)

	writeProcessEvaluatorBinary(b, policy)
	writeFileEvaluatorBinary(b, policy)
	writeNetworkEvaluatorBinary(b, policy)
}

func writeProcessEvaluatorBinary(b *strings.Builder, policy *Policy) {
	rules := rulesForEvent(policy, "process")
	defaultAction := actionConstant(policy.DefaultAction)

	b.WriteString("unsafe fn evaluate_process(base: *const u8) -> i32 {\n")
	b.WriteString("    let pid = read_u32(base, OFF_PID);\n")
	b.WriteString("    let uid = read_u32(base, OFF_UID);\n")
	b.WriteString("    let gid = read_u32(base, OFF_GID);\n")
	b.WriteString("    let comm = read_str(base, OFF_COMM, OFF_COMM_LEN);\n")
	b.WriteString("    let path = read_str(base, OFF_PRIMARY_STR, OFF_PRIMARY_STR_LEN);\n")
	b.WriteString("    let _ = (pid, gid, comm);\n")

	for _, rule := range rules {
		writeRuleCheckBinary(b, rule, "process", globalRuleIndex(policy, rule))
	}
	b.WriteString(fmt.Sprintf("    %s\n", defaultAction))
	b.WriteString("}\n\n")
}

func writeFileEvaluatorBinary(b *strings.Builder, policy *Policy) {
	rules := rulesForEvent(policy, "file")
	defaultAction := actionConstant(policy.DefaultAction)

	b.WriteString("unsafe fn evaluate_file(base: *const u8) -> i32 {\n")
	b.WriteString("    let pid = read_u32(base, OFF_PID);\n")
	b.WriteString("    let uid = read_u32(base, OFF_UID);\n")
	b.WriteString("    let gid = read_u32(base, OFF_GID);\n")
	b.WriteString("    let comm = read_str(base, OFF_COMM, OFF_COMM_LEN);\n")
	b.WriteString("    let path = read_str(base, OFF_PRIMARY_STR, OFF_PRIMARY_STR_LEN);\n")
	b.WriteString("    let flags = read_u32(base, OFF_FLAGS);\n")
	b.WriteString("    let operation = read_str(base, OFF_SECONDARY_STR, OFF_SECONDARY_STR_LEN);\n")
	b.WriteString("    let _ = (pid, gid, comm, flags);\n")

	for _, rule := range rules {
		writeRuleCheckBinary(b, rule, "file", globalRuleIndex(policy, rule))
	}
	b.WriteString(fmt.Sprintf("    %s\n", defaultAction))
	b.WriteString("}\n\n")
}

func writeNetworkEvaluatorBinary(b *strings.Builder, policy *Policy) {
	rules := rulesForEvent(policy, "network")
	defaultAction := actionConstant(policy.DefaultAction)

	b.WriteString("unsafe fn evaluate_network(base: *const u8) -> i32 {\n")
	b.WriteString("    let pid = read_u32(base, OFF_PID);\n")
	b.WriteString("    let uid = read_u32(base, OFF_UID);\n")
	b.WriteString("    let gid = read_u32(base, OFF_GID);\n")
	b.WriteString("    let comm = read_str(base, OFF_COMM, OFF_COMM_LEN);\n")
	b.WriteString("    let remote_addr = read_str(base, OFF_PRIMARY_STR, OFF_PRIMARY_STR_LEN);\n")
	b.WriteString("    let remote_port = read_u16(base, OFF_REMOTE_PORT);\n")
	b.WriteString("    let local_port = read_u16(base, OFF_LOCAL_PORT);\n")
	b.WriteString("    let protocol = read_str(base, OFF_SECONDARY_STR, OFF_SECONDARY_STR_LEN);\n")
	b.WriteString("    let _ = (pid, gid, comm);\n")

	for _, rule := range rules {
		writeRuleCheckBinary(b, rule, "network", globalRuleIndex(policy, rule))
	}
	b.WriteString(fmt.Sprintf("    %s\n", defaultAction))
	b.WriteString("}\n\n")
}

func writeRuleCheckBinary(b *strings.Builder, rule Rule, eventType string, ruleIndex int) {
	action := actionConstant(rule.Action)
	if rule.Mode == "audit" && rule.Action == "deny" {
		action = "ACTION_AUDIT_DENY"
	}

	condExpr := generateConditionExprBinary(rule.Conditions, eventType)
	if condExpr == "" {
		condExpr = "true"
	}

	b.WriteString(fmt.Sprintf("    // Rule: %s\n", rule.Name))
	b.WriteString(fmt.Sprintf("    if %s {\n", condExpr))
	b.WriteString(fmt.Sprintf("        LAST_MATCHED = %d;\n", ruleIndex))
	b.WriteString(fmt.Sprintf("        return %s;\n", action))
	b.WriteString("    }\n\n")
}

func writeGetLastMatchedRule(b *strings.Builder) {
	b.WriteString(`#[no_mangle]
pub extern "C" fn get_last_matched_rule(buf: *mut u8, len: u32) -> u32 {
    unsafe {
        if LAST_MATCHED == 0xFFFFFFFF {
            return 0;
        }
        let idx = LAST_MATCHED as usize;
        if idx >= RULE_REASONS.len() {
            return 0;
        }
        let reason = RULE_REASONS[idx];
        let bytes = reason.as_bytes();
        let copy_len = if bytes.len() < len as usize { bytes.len() } else { len as usize };
        core::ptr::copy_nonoverlapping(bytes.as_ptr(), buf, copy_len);
        copy_len as u32
    }
}

`)
}

func writeHostExterns(b *strings.Builder) {
	b.WriteString(`// Host callback extern declarations (available for hand-written WASM extensions)
extern "C" {
    #[allow(dead_code)]
    fn get_field_u32(field_id: u32) -> u32;
    #[allow(dead_code)]
    fn get_field_str(field_id: u32, buf_ptr: *mut u8, buf_len: u32) -> u32;
}
`)
}

func generateConditionExprBinary(conds Conditions, eventType string) string {
	var parts []string

	if len(conds.All) > 0 {
		allParts := make([]string, 0, len(conds.All))
		for _, c := range conds.All {
			expr := conditionToRustBinary(c, eventType)
			if expr != "" {
				allParts = append(allParts, expr)
			}
		}
		if len(allParts) > 0 {
			parts = append(parts, strings.Join(allParts, " && "))
		}
	}

	if len(conds.Any) > 0 {
		anyParts := make([]string, 0, len(conds.Any))
		for _, c := range conds.Any {
			expr := conditionToRustBinary(c, eventType)
			if expr != "" {
				anyParts = append(anyParts, expr)
			}
		}
		if len(anyParts) > 0 {
			parts = append(parts, fmt.Sprintf("(%s)", strings.Join(anyParts, " || ")))
		}
	}

	if len(conds.Not) > 0 {
		for _, c := range conds.Not {
			expr := conditionToRustBinary(c, eventType)
			if expr != "" {
				parts = append(parts, fmt.Sprintf("!(%s)", expr))
			}
		}
	}

	return strings.Join(parts, " && ")
}

func conditionToRustBinary(c Condition, eventType string) string {
	fieldExpr := fieldToRustBinary(c.Field, eventType)

	switch c.Operator {
	case "eq":
		return formatEqBinary(fieldExpr, c.Field, c.Value)
	case "not":
		return formatNotBinary(fieldExpr, c.Field, c.Value)
	case "glob":
		pattern, _ := c.Value.(string)
		return fmt.Sprintf("matches_glob(%s, %q)", fieldExpr, pattern)
	case "any_of":
		return formatAnyOfBinary(fieldExpr, c.Field, c.Value)
	case "none_of":
		return formatNoneOfBinary(fieldExpr, c.Field, c.Value)
	case "gt":
		return fmt.Sprintf("%s > %s", fieldExpr, formatNumeric(c.Value))
	case "lt":
		return fmt.Sprintf("%s < %s", fieldExpr, formatNumeric(c.Value))
	case "gte":
		return fmt.Sprintf("%s >= %s", fieldExpr, formatNumeric(c.Value))
	case "lte":
		return fmt.Sprintf("%s <= %s", fieldExpr, formatNumeric(c.Value))
	case "starts_with":
		s, _ := c.Value.(string)
		return fmt.Sprintf("str_starts_with(%s, %q)", fieldExpr, s)
	case "contains":
		s, _ := c.Value.(string)
		return fmt.Sprintf("str_contains(%s, %q)", fieldExpr, s)
	default:
		return "true"
	}
}

func fieldToRustBinary(field string, eventType string) string {
	switch field {
	case "pid":
		return "pid"
	case "uid":
		return "uid"
	case "gid":
		return "gid"
	case "comm":
		return "comm"
	case "path":
		if eventType == "process" {
			return "path"
		}
		return "path"
	case "args":
		return "path"
	case "operation":
		return "operation"
	case "protocol":
		return "protocol"
	case "remote_addr":
		return "remote_addr"
	case "flags":
		return "flags"
	case "remote_port":
		return "remote_port"
	case "local_port":
		return "local_port"
	default:
		return field
	}
}

func formatEqBinary(fieldExpr, field string, value interface{}) string {
	if isNumericField(field) {
		return fmt.Sprintf("%s == %s", fieldExpr, formatNumeric(value))
	}
	s := fmt.Sprintf("%v", value)
	return fmt.Sprintf("%s == %q", fieldExpr, s)
}

func formatNotBinary(fieldExpr, field string, value interface{}) string {
	if isNumericField(field) {
		return fmt.Sprintf("%s != %s", fieldExpr, formatNumeric(value))
	}
	s := fmt.Sprintf("%v", value)
	return fmt.Sprintf("%s != %q", fieldExpr, s)
}

func formatAnyOfBinary(fieldExpr, field string, value interface{}) string {
	items := toSlice(value)
	if isNumericField(field) {
		rustType := fieldRustType(field)
		vals := make([]string, 0, len(items))
		for _, item := range items {
			vals = append(vals, formatNumeric(item))
		}
		return fmt.Sprintf("any_of_%s(%s, &[%s])", rustType, fieldExpr, strings.Join(vals, ", "))
	}
	vals := make([]string, 0, len(items))
	for _, item := range items {
		vals = append(vals, fmt.Sprintf("%q", fmt.Sprintf("%v", item)))
	}
	return fmt.Sprintf("any_of_str(%s, &[%s])", fieldExpr, strings.Join(vals, ", "))
}

func formatNoneOfBinary(fieldExpr, field string, value interface{}) string {
	items := toSlice(value)
	if isNumericField(field) {
		rustType := fieldRustType(field)
		vals := make([]string, 0, len(items))
		for _, item := range items {
			vals = append(vals, formatNumeric(item))
		}
		return fmt.Sprintf("none_of_%s(%s, &[%s])", rustType, fieldExpr, strings.Join(vals, ", "))
	}
	vals := make([]string, 0, len(items))
	for _, item := range items {
		vals = append(vals, fmt.Sprintf("%q", fmt.Sprintf("%v", item)))
	}
	return fmt.Sprintf("none_of_str(%s, &[%s])", fieldExpr, strings.Join(vals, ", "))
}

func globalRuleIndex(policy *Policy, rule Rule) int {
	for i, r := range policy.Rules {
		if r.Name == rule.Name {
			return i
		}
	}
	return 0
}

func isNumericField(field string) bool {
	switch field {
	case "pid", "uid", "gid", "flags", "remote_port", "local_port":
		return true
	default:
		return false
	}
}

func fieldRustType(field string) string {
	switch field {
	case "pid", "uid", "gid", "flags":
		return "u32"
	case "remote_port", "local_port":
		return "u16"
	default:
		return "str"
	}
}

func formatNumeric(value interface{}) string {
	switch v := value.(type) {
	case int:
		return fmt.Sprintf("%d", v)
	case int64:
		return fmt.Sprintf("%d", v)
	case float64:
		if v == float64(int64(v)) {
			return fmt.Sprintf("%d", int64(v))
		}
		return fmt.Sprintf("%v", v)
	default:
		return fmt.Sprintf("%v", v)
	}
}

func toSlice(value interface{}) []interface{} {
	switch v := value.(type) {
	case []interface{}:
		return v
	case []string:
		result := make([]interface{}, len(v))
		for i, s := range v {
			result[i] = s
		}
		return result
	default:
		return []interface{}{value}
	}
}

func rulesForEvent(policy *Policy, eventType string) []Rule {
	var rules []Rule
	for _, r := range policy.Rules {
		if r.Event == eventType {
			rules = append(rules, r)
		}
	}
	return rules
}

func actionConstant(action string) string {
	switch action {
	case "allow":
		return "ACTION_ALLOW"
	case "deny":
		return "ACTION_DENY"
	case "log":
		return "ACTION_LOG"
	default:
		return "ACTION_ALLOW"
	}
}

func GenerateCargoToml(policyName string) string {
	safeName := strings.ReplaceAll(policyName, "-", "_")
	safeName = strings.ReplaceAll(safeName, " ", "_")

	return fmt.Sprintf(`[package]
name = "warmor-policy-%s"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
`, safeName)
}
