package compiler

import (
	"fmt"
	"strings"
)

func GenerateRust(policy *Policy) (string, error) {
	var b strings.Builder

	b.WriteString(fmt.Sprintf("// Auto-generated by warmor-compile from: %s\n", policy.Name))
	b.WriteString("// DO NOT EDIT — regenerate from the source YAML policy.\n\n")
	b.WriteString("use serde::Deserialize;\nuse std::slice;\n\n")
	b.WriteString("const ACTION_ALLOW: i32 = 0;\nconst ACTION_DENY: i32 = 1;\nconst ACTION_LOG: i32 = 2;\n\n")

	writeEventStructs(&b)
	writeHelperFunctions(&b)
	writeMallocFree(&b)
	writeEvaluateFunction(&b, policy)

	return b.String(), nil
}

func writeEventStructs(b *strings.Builder) {
	b.WriteString(`#[derive(Deserialize)]
#[serde(tag = "type")]
enum Event {
    #[serde(rename = "PROCESS")]
    Process(ProcessEvent),
    #[serde(rename = "FILE")]
    File(FileEvent),
    #[serde(rename = "NETWORK")]
    Network(NetworkEvent),
}

#[derive(Deserialize)]
#[allow(dead_code)]
struct ProcessEvent {
    pid: u32,
    uid: u32,
    gid: u32,
    comm: String,
    filename: String,
}

#[derive(Deserialize)]
#[allow(dead_code)]
struct FileEvent {
    pid: u32,
    uid: u32,
    gid: u32,
    comm: String,
    operation: String,
    path: String,
    flags: u32,
}

#[derive(Deserialize)]
#[allow(dead_code)]
struct NetworkEvent {
    pid: u32,
    uid: u32,
    gid: u32,
    comm: String,
    operation: String,
    protocol: String,
    remote_addr: String,
    remote_port: u16,
    local_port: u16,
}

`)
}

func writeMallocFree(b *strings.Builder) {
	b.WriteString(`#[no_mangle]
pub extern "C" fn malloc(size: usize) -> *mut u8 {
    let mut buf = Vec::with_capacity(size);
    let ptr = buf.as_mut_ptr();
    std::mem::forget(buf);
    ptr
}

#[no_mangle]
pub extern "C" fn free(ptr: *mut u8, size: usize) {
    unsafe {
        let _ = Vec::from_raw_parts(ptr, 0, size);
    }
}

`)
}

func writeHelperFunctions(b *strings.Builder) {
	b.WriteString(`fn matches_glob(s: &str, pattern: &str) -> bool {
    glob_match(s.as_bytes(), pattern.as_bytes())
}

fn glob_match(s: &[u8], p: &[u8]) -> bool {
    let mut si = 0;
    let mut pi = 0;
    let mut star_pi = usize::MAX;
    let mut star_si = 0;

    while si < s.len() {
        if pi < p.len() && p[pi] == b'*' {
            if pi + 1 < p.len() && p[pi + 1] == b'*' {
                // "**" matches everything including path separators
                pi += 2;
                if pi < p.len() && p[pi] == b'/' {
                    pi += 1;
                }
                star_pi = pi;
                star_si = si;
            } else {
                // "*" matches everything except path separators
                pi += 1;
                star_pi = pi;
                star_si = si;
            }
        } else if pi < p.len() && (p[pi] == b'?' || p[pi] == s[si]) {
            si += 1;
            pi += 1;
        } else if star_pi != usize::MAX {
            pi = star_pi;
            star_si += 1;
            si = star_si;
        } else {
            return false;
        }
    }

    while pi < p.len() && p[pi] == b'*' {
        pi += 1;
    }

    pi == p.len()
}

fn any_of_str(s: &str, values: &[&str]) -> bool {
    values.iter().any(|v| *v == s)
}

fn none_of_str(s: &str, values: &[&str]) -> bool {
    !any_of_str(s, values)
}

fn any_of_u32(val: u32, values: &[u32]) -> bool {
    values.contains(&val)
}

fn none_of_u32(val: u32, values: &[u32]) -> bool {
    !values.contains(&val)
}

fn any_of_u16(val: u16, values: &[u16]) -> bool {
    values.contains(&val)
}

fn none_of_u16(val: u16, values: &[u16]) -> bool {
    !values.contains(&val)
}

`)
}

func writeEvaluateFunction(b *strings.Builder, policy *Policy) {
	b.WriteString(`#[no_mangle]
pub extern "C" fn evaluate_syscall(event_ptr: *const u8, event_len: usize) -> i32 {
    let event_bytes = unsafe { slice::from_raw_parts(event_ptr, event_len) };
    let event: Event = match serde_json::from_slice(event_bytes) {
        Ok(e) => e,
        Err(_) => return ACTION_DENY,
    };

    match event {
        Event::Process(ref e) => evaluate_process(e),
        Event::File(ref e) => evaluate_file(e),
        Event::Network(ref e) => evaluate_network(e),
    }
}

`)

	writeProcessEvaluator(b, policy)
	writeFileEvaluator(b, policy)
	writeNetworkEvaluator(b, policy)
}

func writeProcessEvaluator(b *strings.Builder, policy *Policy) {
	rules := rulesForEvent(policy, "process")
	defaultAction := actionConstant(policy.DefaultAction)

	b.WriteString("fn evaluate_process(event: &ProcessEvent) -> i32 {\n")
	for _, rule := range rules {
		writeRuleCheck(b, rule, "process")
	}
	b.WriteString(fmt.Sprintf("    %s\n", defaultAction))
	b.WriteString("}\n\n")
}

func writeFileEvaluator(b *strings.Builder, policy *Policy) {
	rules := rulesForEvent(policy, "file")
	defaultAction := actionConstant(policy.DefaultAction)

	b.WriteString("fn evaluate_file(event: &FileEvent) -> i32 {\n")
	for _, rule := range rules {
		writeRuleCheck(b, rule, "file")
	}
	b.WriteString(fmt.Sprintf("    %s\n", defaultAction))
	b.WriteString("}\n\n")
}

func writeNetworkEvaluator(b *strings.Builder, policy *Policy) {
	rules := rulesForEvent(policy, "network")
	defaultAction := actionConstant(policy.DefaultAction)

	b.WriteString("fn evaluate_network(event: &NetworkEvent) -> i32 {\n")
	for _, rule := range rules {
		writeRuleCheck(b, rule, "network")
	}
	b.WriteString(fmt.Sprintf("    %s\n", defaultAction))
	b.WriteString("}\n\n")
}

func writeRuleCheck(b *strings.Builder, rule Rule, eventType string) {
	action := actionConstant(rule.Action)

	condExpr := generateConditionExpr(rule.Conditions, eventType)
	if condExpr == "" {
		condExpr = "true"
	}

	b.WriteString(fmt.Sprintf("    // Rule: %s\n", rule.Name))
	b.WriteString(fmt.Sprintf("    if %s {\n", condExpr))
	b.WriteString(fmt.Sprintf("        return %s;\n", action))
	b.WriteString("    }\n\n")
}

func generateConditionExpr(conds Conditions, eventType string) string {
	var parts []string

	if len(conds.All) > 0 {
		allParts := make([]string, 0, len(conds.All))
		for _, c := range conds.All {
			expr := conditionToRust(c, eventType)
			if expr != "" {
				allParts = append(allParts, expr)
			}
		}
		if len(allParts) > 0 {
			parts = append(parts, strings.Join(allParts, " && "))
		}
	}

	if len(conds.Any) > 0 {
		anyParts := make([]string, 0, len(conds.Any))
		for _, c := range conds.Any {
			expr := conditionToRust(c, eventType)
			if expr != "" {
				anyParts = append(anyParts, expr)
			}
		}
		if len(anyParts) > 0 {
			parts = append(parts, fmt.Sprintf("(%s)", strings.Join(anyParts, " || ")))
		}
	}

	if len(conds.Not) > 0 {
		for _, c := range conds.Not {
			expr := conditionToRust(c, eventType)
			if expr != "" {
				parts = append(parts, fmt.Sprintf("!(%s)", expr))
			}
		}
	}

	return strings.Join(parts, " && ")
}

func conditionToRust(c Condition, eventType string) string {
	fieldExpr := fieldToRust(c.Field, eventType)

	switch c.Operator {
	case "eq":
		return formatEq(fieldExpr, c.Field, c.Value)
	case "not":
		return formatNot(fieldExpr, c.Field, c.Value)
	case "glob":
		pattern, _ := c.Value.(string)
		return fmt.Sprintf("matches_glob(&%s, %q)", fieldExpr, pattern)
	case "any_of":
		return formatAnyOf(fieldExpr, c.Field, c.Value)
	case "none_of":
		return formatNoneOf(fieldExpr, c.Field, c.Value)
	case "gt":
		return fmt.Sprintf("%s > %s", fieldExpr, formatNumeric(c.Value))
	case "lt":
		return fmt.Sprintf("%s < %s", fieldExpr, formatNumeric(c.Value))
	case "gte":
		return fmt.Sprintf("%s >= %s", fieldExpr, formatNumeric(c.Value))
	case "lte":
		return fmt.Sprintf("%s <= %s", fieldExpr, formatNumeric(c.Value))
	case "starts_with":
		s, _ := c.Value.(string)
		return fmt.Sprintf("%s.starts_with(%q)", fieldExpr, s)
	case "contains":
		s, _ := c.Value.(string)
		return fmt.Sprintf("%s.contains(%q)", fieldExpr, s)
	default:
		return "true"
	}
}

func fieldToRust(field string, eventType string) string {
	switch field {
	case "path":
		if eventType == "process" {
			return "event.filename"
		}
		return "event.path"
	case "args":
		return "event.filename"
	default:
		return "event." + field
	}
}

func isNumericField(field string) bool {
	switch field {
	case "pid", "uid", "gid", "flags", "remote_port", "local_port":
		return true
	default:
		return false
	}
}

func fieldRustType(field string) string {
	switch field {
	case "pid", "uid", "gid", "flags":
		return "u32"
	case "remote_port", "local_port":
		return "u16"
	default:
		return "str"
	}
}

func formatEq(fieldExpr, field string, value interface{}) string {
	if isNumericField(field) {
		return fmt.Sprintf("%s == %s", fieldExpr, formatNumeric(value))
	}
	s := fmt.Sprintf("%v", value)
	return fmt.Sprintf("%s == %q", fieldExpr, s)
}

func formatNot(fieldExpr, field string, value interface{}) string {
	if isNumericField(field) {
		return fmt.Sprintf("%s != %s", fieldExpr, formatNumeric(value))
	}
	s := fmt.Sprintf("%v", value)
	return fmt.Sprintf("%s != %q", fieldExpr, s)
}

func formatAnyOf(fieldExpr, field string, value interface{}) string {
	items := toSlice(value)
	if isNumericField(field) {
		rustType := fieldRustType(field)
		vals := make([]string, 0, len(items))
		for _, item := range items {
			vals = append(vals, formatNumeric(item))
		}
		return fmt.Sprintf("any_of_%s(%s, &[%s])", rustType, fieldExpr, strings.Join(vals, ", "))
	}
	vals := make([]string, 0, len(items))
	for _, item := range items {
		vals = append(vals, fmt.Sprintf("%q", fmt.Sprintf("%v", item)))
	}
	return fmt.Sprintf("any_of_str(&%s, &[%s])", fieldExpr, strings.Join(vals, ", "))
}

func formatNoneOf(fieldExpr, field string, value interface{}) string {
	items := toSlice(value)
	if isNumericField(field) {
		rustType := fieldRustType(field)
		vals := make([]string, 0, len(items))
		for _, item := range items {
			vals = append(vals, formatNumeric(item))
		}
		return fmt.Sprintf("none_of_%s(%s, &[%s])", rustType, fieldExpr, strings.Join(vals, ", "))
	}
	vals := make([]string, 0, len(items))
	for _, item := range items {
		vals = append(vals, fmt.Sprintf("%q", fmt.Sprintf("%v", item)))
	}
	return fmt.Sprintf("none_of_str(&%s, &[%s])", fieldExpr, strings.Join(vals, ", "))
}

func formatNumeric(value interface{}) string {
	switch v := value.(type) {
	case int:
		return fmt.Sprintf("%d", v)
	case int64:
		return fmt.Sprintf("%d", v)
	case float64:
		if v == float64(int64(v)) {
			return fmt.Sprintf("%d", int64(v))
		}
		return fmt.Sprintf("%v", v)
	default:
		return fmt.Sprintf("%v", v)
	}
}

func toSlice(value interface{}) []interface{} {
	switch v := value.(type) {
	case []interface{}:
		return v
	case []string:
		result := make([]interface{}, len(v))
		for i, s := range v {
			result[i] = s
		}
		return result
	default:
		return []interface{}{value}
	}
}

func rulesForEvent(policy *Policy, eventType string) []Rule {
	var rules []Rule
	for _, r := range policy.Rules {
		if r.Event == eventType {
			rules = append(rules, r)
		}
	}
	return rules
}

func actionConstant(action string) string {
	switch action {
	case "allow":
		return "ACTION_ALLOW"
	case "deny":
		return "ACTION_DENY"
	case "log":
		return "ACTION_LOG"
	default:
		return "ACTION_ALLOW"
	}
}

func GenerateCargoToml(policyName string) string {
	safeName := strings.ReplaceAll(policyName, "-", "_")
	safeName = strings.ReplaceAll(safeName, " ", "_")

	return fmt.Sprintf(`[package]
name = "warmor-policy-%s"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
`, safeName)
}
