apiVersion: v2
name: warmor
description: WASM-powered cross-platform security enforcer
type: application
version: 0.2.0
appVersion: "1.1.0-beta"
keywords:
  - security
  - ebpf
  - wasm
  - runtime-security
home: https://github.com/yasindce1998/warmor
maintainers:
  - name: Mohammed Yasin
    url: https://github.com/yasindce1998
