// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type connect_monitorNetworkEvent struct {
	Pid          uint32
	Uid          uint32
	Gid          uint32
	Comm         [16]int8
	Family       uint16
	RemotePort   uint16
	RemoteAddrV4 uint32
	RemoteAddrV6 [16]uint8
	_            [4]byte
	Timestamp    uint64
	CgroupId     uint64
}

// loadConnect_monitor returns the embedded CollectionSpec for connect_monitor.
func loadConnect_monitor() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Connect_monitorBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load connect_monitor: %w", err)
	}

	return spec, err
}

// loadConnect_monitorObjects loads connect_monitor and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*connect_monitorObjects
//	*connect_monitorPrograms
//	*connect_monitorMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadConnect_monitorObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadConnect_monitor()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// connect_monitorSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type connect_monitorSpecs struct {
	connect_monitorProgramSpecs
	connect_monitorMapSpecs
	connect_monitorVariableSpecs
}

// connect_monitorProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type connect_monitorProgramSpecs struct {
	TracepointSyscallsSysEnterConnect *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_connect"`
}

// connect_monitorMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type connect_monitorMapSpecs struct {
	CgroupFilter  *ebpf.MapSpec `ebpf:"cgroup_filter"`
	NetworkEvents *ebpf.MapSpec `ebpf:"network_events"`
}

// connect_monitorVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type connect_monitorVariableSpecs struct {
	UnusedNetworkEvent *ebpf.VariableSpec `ebpf:"unused_network_event"`
}

// connect_monitorObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadConnect_monitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type connect_monitorObjects struct {
	connect_monitorPrograms
	connect_monitorMaps
	connect_monitorVariables
}

func (o *connect_monitorObjects) Close() error {
	return _Connect_monitorClose(
		&o.connect_monitorPrograms,
		&o.connect_monitorMaps,
	)
}

// connect_monitorMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadConnect_monitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type connect_monitorMaps struct {
	CgroupFilter  *ebpf.Map `ebpf:"cgroup_filter"`
	NetworkEvents *ebpf.Map `ebpf:"network_events"`
}

func (m *connect_monitorMaps) Close() error {
	return _Connect_monitorClose(
		m.CgroupFilter,
		m.NetworkEvents,
	)
}

// connect_monitorVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadConnect_monitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type connect_monitorVariables struct {
	UnusedNetworkEvent *ebpf.Variable `ebpf:"unused_network_event"`
}

// connect_monitorPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadConnect_monitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type connect_monitorPrograms struct {
	TracepointSyscallsSysEnterConnect *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_connect"`
}

func (p *connect_monitorPrograms) Close() error {
	return _Connect_monitorClose(
		p.TracepointSyscallsSysEnterConnect,
	)
}

func _Connect_monitorClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed connect_monitor_bpfeb.o
var _Connect_monitorBytes []byte
