// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type execve_monitorExecveEvent struct {
	Pid       uint32
	Uid       uint32
	Gid       uint32
	Comm      [16]int8
	Filename  [256]int8
	_         [4]byte
	Timestamp uint64
	CgroupId  uint64
}

// loadExecve_monitor returns the embedded CollectionSpec for execve_monitor.
func loadExecve_monitor() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Execve_monitorBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load execve_monitor: %w", err)
	}

	return spec, err
}

// loadExecve_monitorObjects loads execve_monitor and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*execve_monitorObjects
//	*execve_monitorPrograms
//	*execve_monitorMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadExecve_monitorObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadExecve_monitor()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// execve_monitorSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type execve_monitorSpecs struct {
	execve_monitorProgramSpecs
	execve_monitorMapSpecs
	execve_monitorVariableSpecs
}

// execve_monitorProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type execve_monitorProgramSpecs struct {
	TracepointSyscallsSysEnterExecve *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_execve"`
}

// execve_monitorMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type execve_monitorMapSpecs struct {
	CgroupFilter *ebpf.MapSpec `ebpf:"cgroup_filter"`
	Events       *ebpf.MapSpec `ebpf:"events"`
}

// execve_monitorVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type execve_monitorVariableSpecs struct {
	UnusedExecveEvent *ebpf.VariableSpec `ebpf:"unused_execve_event"`
}

// execve_monitorObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadExecve_monitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type execve_monitorObjects struct {
	execve_monitorPrograms
	execve_monitorMaps
	execve_monitorVariables
}

func (o *execve_monitorObjects) Close() error {
	return _Execve_monitorClose(
		&o.execve_monitorPrograms,
		&o.execve_monitorMaps,
	)
}

// execve_monitorMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadExecve_monitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type execve_monitorMaps struct {
	CgroupFilter *ebpf.Map `ebpf:"cgroup_filter"`
	Events       *ebpf.Map `ebpf:"events"`
}

func (m *execve_monitorMaps) Close() error {
	return _Execve_monitorClose(
		m.CgroupFilter,
		m.Events,
	)
}

// execve_monitorVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadExecve_monitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type execve_monitorVariables struct {
	UnusedExecveEvent *ebpf.Variable `ebpf:"unused_execve_event"`
}

// execve_monitorPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadExecve_monitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type execve_monitorPrograms struct {
	TracepointSyscallsSysEnterExecve *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_execve"`
}

func (p *execve_monitorPrograms) Close() error {
	return _Execve_monitorClose(
		p.TracepointSyscallsSysEnterExecve,
	)
}

func _Execve_monitorClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed execve_monitor_bpfel.o
var _Execve_monitorBytes []byte
