//go:build linux
// +build linux

package ebpf

import (
	"github.com/cilium/ebpf"
)

// This file contains stub type definitions that would normally be generated by bpf2go
// These stubs allow the code to compile on Linux before running go generate
// Once you run 'go generate ./internal/ebpf', these will be replaced by actual generated code

// execve_monitorObjects contains all objects after they have been loaded into the kernel.
type execve_monitorObjects struct {
	execve_monitorPrograms
	execve_monitorMaps
}

// execve_monitorPrograms contains all programs after they have been loaded into the kernel.
type execve_monitorPrograms struct {
	TracepointSyscallsSysEnterExecve *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_execve"`
}

// execve_monitorMaps contains all maps after they have been loaded into the kernel.
type execve_monitorMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

// Close releases all resources held by the objects.
func (o *execve_monitorObjects) Close() error {
	return nil
}

// loadExecve_monitorObjects loads bpf objects into the kernel.
func loadExecve_monitorObjects(obj *execve_monitorObjects, opts *ebpf.CollectionOptions) error {
	// This is a stub - the real implementation will be generated by bpf2go
	// When you run: go generate ./internal/ebpf
	return nil
}

// NOTE: This file should be deleted after running 'go generate ./internal/ebpf'
// The actual generated files will be:
// - execve_monitor_bpfeb.go (big-endian)
// - execve_monitor_bpfel.go (little-endian)

// Made with Bob
