//go:build linux

package ebpf

import (
	"github.com/cilium/ebpf"
)

// Stub type definitions that would normally be generated by bpf2go.
// These allow the code to compile on Linux before running go generate.
// After running 'go generate ./internal/ebpf', delete this file — the real
// generated files (*_bpfeb.go / *_bpfel.go) will replace these.

// --- execve_monitor ---

type execve_monitorObjects struct {
	execve_monitorPrograms
	execve_monitorMaps
}

type execve_monitorPrograms struct {
	TracepointSyscallsSysEnterExecve *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_execve"`
}

type execve_monitorMaps struct {
	Events       *ebpf.Map `ebpf:"events"`
	CgroupFilter *ebpf.Map `ebpf:"cgroup_filter"`
}

func (o *execve_monitorObjects) Close() error { return nil }

func loadExecve_monitorObjects(obj *execve_monitorObjects, opts *ebpf.CollectionOptions) error {
	return nil
}

// --- openat_monitor ---

type openat_monitorObjects struct {
	openat_monitorPrograms
	openat_monitorMaps
}

type openat_monitorPrograms struct {
	TracepointSyscallsSysEnterOpenat *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_openat"`
}

type openat_monitorMaps struct {
	FileEvents   *ebpf.Map `ebpf:"file_events"`
	CgroupFilter *ebpf.Map `ebpf:"cgroup_filter"`
}

func (o *openat_monitorObjects) Close() error { return nil }

func loadOpenat_monitorObjects(obj *openat_monitorObjects, opts *ebpf.CollectionOptions) error {
	return nil
}

// --- connect_monitor ---

type connect_monitorObjects struct {
	connect_monitorPrograms
	connect_monitorMaps
}

type connect_monitorPrograms struct {
	TracepointSyscallsSysEnterConnect *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_connect"`
}

type connect_monitorMaps struct {
	NetworkEvents *ebpf.Map `ebpf:"network_events"`
	CgroupFilter  *ebpf.Map `ebpf:"cgroup_filter"`
}

func (o *connect_monitorObjects) Close() error { return nil }

func loadConnect_monitorObjects(obj *connect_monitorObjects, opts *ebpf.CollectionOptions) error {
	return nil
}

// --- lsm_exec ---

type lsm_execObjects struct {
	lsm_execPrograms
	lsm_execMaps
}

type lsm_execPrograms struct {
	LsmExecCheck *ebpf.Program `ebpf:"lsm_exec_check"`
}

type lsm_execMaps struct {
	PolicyMap      *ebpf.Map `ebpf:"policy_map"`
	LsmEvents      *ebpf.Map `ebpf:"lsm_events"`
	LsmCgroupFilter *ebpf.Map `ebpf:"lsm_cgroup_filter"`
	LsmEnforce     *ebpf.Map `ebpf:"lsm_enforce"`
}

func (o *lsm_execObjects) Close() error { return nil }

func loadLsm_execObjects(_ *lsm_execObjects, _ *ebpf.CollectionOptions) error {
	return nil
}

// --- lsm_file ---

type lsm_fileObjects struct {
	lsm_filePrograms
	lsm_fileMaps
}

type lsm_filePrograms struct {
	LsmFileCheck *ebpf.Program `ebpf:"lsm_file_check"`
}

type lsm_fileMaps struct {
	PolicyMap      *ebpf.Map `ebpf:"policy_map"`
	LsmEvents      *ebpf.Map `ebpf:"lsm_events"`
	LsmCgroupFilter *ebpf.Map `ebpf:"lsm_cgroup_filter"`
	LsmEnforce     *ebpf.Map `ebpf:"lsm_enforce"`
}

func (o *lsm_fileObjects) Close() error { return nil }

func loadLsm_fileObjects(_ *lsm_fileObjects, _ *ebpf.CollectionOptions) error {
	return nil
}

// --- lsm_connect ---

type lsm_connectObjects struct {
	lsm_connectPrograms
	lsm_connectMaps
}

type lsm_connectPrograms struct {
	LsmConnectCheck *ebpf.Program `ebpf:"lsm_connect_check"`
}

type lsm_connectMaps struct {
	PolicyMap      *ebpf.Map `ebpf:"policy_map"`
	LsmEvents      *ebpf.Map `ebpf:"lsm_events"`
	LsmCgroupFilter *ebpf.Map `ebpf:"lsm_cgroup_filter"`
	LsmEnforce     *ebpf.Map `ebpf:"lsm_enforce"`
}

func (o *lsm_connectObjects) Close() error { return nil }

func loadLsm_connectObjects(_ *lsm_connectObjects, _ *ebpf.CollectionOptions) error {
	return nil
}
