//go:build linux

package ebpf

import (
	"github.com/cilium/ebpf"
)

// Stub type definitions that would normally be generated by bpf2go.
// These allow the code to compile on Linux before running go generate.
// After running 'go generate ./internal/ebpf', delete this file — the real
// generated files (*_bpfeb.go / *_bpfel.go) will replace these.

// --- execve_monitor ---

type execve_monitorObjects struct {
	execve_monitorPrograms
	execve_monitorMaps
}

type execve_monitorPrograms struct {
	TracepointSyscallsSysEnterExecve *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_execve"`
}

type execve_monitorMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (o *execve_monitorObjects) Close() error { return nil }

func loadExecve_monitorObjects(obj *execve_monitorObjects, opts *ebpf.CollectionOptions) error {
	return nil
}

// --- openat_monitor ---

type openat_monitorObjects struct {
	openat_monitorPrograms
	openat_monitorMaps
}

type openat_monitorPrograms struct {
	TracepointSyscallsSysEnterOpenat *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_openat"`
}

type openat_monitorMaps struct {
	FileEvents *ebpf.Map `ebpf:"file_events"`
}

func (o *openat_monitorObjects) Close() error { return nil }

func loadOpenat_monitorObjects(obj *openat_monitorObjects, opts *ebpf.CollectionOptions) error {
	return nil
}

// --- connect_monitor ---

type connect_monitorObjects struct {
	connect_monitorPrograms
	connect_monitorMaps
}

type connect_monitorPrograms struct {
	TracepointSyscallsSysEnterConnect *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_connect"`
}

type connect_monitorMaps struct {
	NetworkEvents *ebpf.Map `ebpf:"network_events"`
}

func (o *connect_monitorObjects) Close() error { return nil }

func loadConnect_monitorObjects(obj *connect_monitorObjects, opts *ebpf.CollectionOptions) error {
	return nil
}
