// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type lsm_ptracePolicyKey struct {
	CgroupId  uint64
	RuleHash  uint32
	EventType uint8
	Pad       [3]uint8
}

type lsm_ptracePolicyValue struct {
	Action   uint8
	Audit    uint8
	Pad      uint16
	HitCount uint32
}

// loadLsm_ptrace returns the embedded CollectionSpec for lsm_ptrace.
func loadLsm_ptrace() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Lsm_ptraceBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load lsm_ptrace: %w", err)
	}

	return spec, err
}

// loadLsm_ptraceObjects loads lsm_ptrace and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*lsm_ptraceObjects
//	*lsm_ptracePrograms
//	*lsm_ptraceMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadLsm_ptraceObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadLsm_ptrace()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// lsm_ptraceSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsm_ptraceSpecs struct {
	lsm_ptraceProgramSpecs
	lsm_ptraceMapSpecs
	lsm_ptraceVariableSpecs
}

// lsm_ptraceProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsm_ptraceProgramSpecs struct {
	LsmPtraceCheck *ebpf.ProgramSpec `ebpf:"lsm_ptrace_check"`
}

// lsm_ptraceMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsm_ptraceMapSpecs struct {
	LsmCgroupFilter *ebpf.MapSpec `ebpf:"lsm_cgroup_filter"`
	LsmEnforce      *ebpf.MapSpec `ebpf:"lsm_enforce"`
	LsmEvents       *ebpf.MapSpec `ebpf:"lsm_events"`
	PolicyMap       *ebpf.MapSpec `ebpf:"policy_map"`
}

// lsm_ptraceVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsm_ptraceVariableSpecs struct {
	UnusedPolicyKey   *ebpf.VariableSpec `ebpf:"unused_policy_key"`
	UnusedPolicyValue *ebpf.VariableSpec `ebpf:"unused_policy_value"`
	UnusedWarmorEvent *ebpf.VariableSpec `ebpf:"unused_warmor_event"`
}

// lsm_ptraceObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadLsm_ptraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsm_ptraceObjects struct {
	lsm_ptracePrograms
	lsm_ptraceMaps
	lsm_ptraceVariables
}

func (o *lsm_ptraceObjects) Close() error {
	return _Lsm_ptraceClose(
		&o.lsm_ptracePrograms,
		&o.lsm_ptraceMaps,
	)
}

// lsm_ptraceMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadLsm_ptraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsm_ptraceMaps struct {
	LsmCgroupFilter *ebpf.Map `ebpf:"lsm_cgroup_filter"`
	LsmEnforce      *ebpf.Map `ebpf:"lsm_enforce"`
	LsmEvents       *ebpf.Map `ebpf:"lsm_events"`
	PolicyMap       *ebpf.Map `ebpf:"policy_map"`
}

func (m *lsm_ptraceMaps) Close() error {
	return _Lsm_ptraceClose(
		m.LsmCgroupFilter,
		m.LsmEnforce,
		m.LsmEvents,
		m.PolicyMap,
	)
}

// lsm_ptraceVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadLsm_ptraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsm_ptraceVariables struct {
	UnusedPolicyKey   *ebpf.Variable `ebpf:"unused_policy_key"`
	UnusedPolicyValue *ebpf.Variable `ebpf:"unused_policy_value"`
	UnusedWarmorEvent *ebpf.Variable `ebpf:"unused_warmor_event"`
}

// lsm_ptracePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadLsm_ptraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsm_ptracePrograms struct {
	LsmPtraceCheck *ebpf.Program `ebpf:"lsm_ptrace_check"`
}

func (p *lsm_ptracePrograms) Close() error {
	return _Lsm_ptraceClose(
		p.LsmPtraceCheck,
	)
}

func _Lsm_ptraceClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed lsm_ptrace_bpfel.o
var _Lsm_ptraceBytes []byte
