// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type lsm_listenPolicyKey struct {
	CgroupId  uint64
	RuleHash  uint32
	EventType uint8
	Pad       [3]uint8
}

type lsm_listenPolicyValue struct {
	Action   uint8
	Audit    uint8
	Pad      uint16
	HitCount uint32
}

// loadLsm_listen returns the embedded CollectionSpec for lsm_listen.
func loadLsm_listen() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Lsm_listenBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load lsm_listen: %w", err)
	}

	return spec, err
}

// loadLsm_listenObjects loads lsm_listen and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*lsm_listenObjects
//	*lsm_listenPrograms
//	*lsm_listenMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadLsm_listenObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadLsm_listen()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// lsm_listenSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsm_listenSpecs struct {
	lsm_listenProgramSpecs
	lsm_listenMapSpecs
	lsm_listenVariableSpecs
}

// lsm_listenProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsm_listenProgramSpecs struct {
	LsmListenCheck *ebpf.ProgramSpec `ebpf:"lsm_listen_check"`
}

// lsm_listenMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsm_listenMapSpecs struct {
	LsmCgroupFilter *ebpf.MapSpec `ebpf:"lsm_cgroup_filter"`
	LsmEnforce      *ebpf.MapSpec `ebpf:"lsm_enforce"`
	LsmEvents       *ebpf.MapSpec `ebpf:"lsm_events"`
	PolicyMap       *ebpf.MapSpec `ebpf:"policy_map"`
}

// lsm_listenVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsm_listenVariableSpecs struct {
	UnusedPolicyKey   *ebpf.VariableSpec `ebpf:"unused_policy_key"`
	UnusedPolicyValue *ebpf.VariableSpec `ebpf:"unused_policy_value"`
	UnusedWarmorEvent *ebpf.VariableSpec `ebpf:"unused_warmor_event"`
}

// lsm_listenObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadLsm_listenObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsm_listenObjects struct {
	lsm_listenPrograms
	lsm_listenMaps
	lsm_listenVariables
}

func (o *lsm_listenObjects) Close() error {
	return _Lsm_listenClose(
		&o.lsm_listenPrograms,
		&o.lsm_listenMaps,
	)
}

// lsm_listenMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadLsm_listenObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsm_listenMaps struct {
	LsmCgroupFilter *ebpf.Map `ebpf:"lsm_cgroup_filter"`
	LsmEnforce      *ebpf.Map `ebpf:"lsm_enforce"`
	LsmEvents       *ebpf.Map `ebpf:"lsm_events"`
	PolicyMap       *ebpf.Map `ebpf:"policy_map"`
}

func (m *lsm_listenMaps) Close() error {
	return _Lsm_listenClose(
		m.LsmCgroupFilter,
		m.LsmEnforce,
		m.LsmEvents,
		m.PolicyMap,
	)
}

// lsm_listenVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadLsm_listenObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsm_listenVariables struct {
	UnusedPolicyKey   *ebpf.Variable `ebpf:"unused_policy_key"`
	UnusedPolicyValue *ebpf.Variable `ebpf:"unused_policy_value"`
	UnusedWarmorEvent *ebpf.Variable `ebpf:"unused_warmor_event"`
}

// lsm_listenPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadLsm_listenObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsm_listenPrograms struct {
	LsmListenCheck *ebpf.Program `ebpf:"lsm_listen_check"`
}

func (p *lsm_listenPrograms) Close() error {
	return _Lsm_listenClose(
		p.LsmListenCheck,
	)
}

func _Lsm_listenClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed lsm_listen_bpfel.o
var _Lsm_listenBytes []byte
