// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type lsm_mountPolicyKey struct {
	CgroupId  uint64
	RuleHash  uint32
	EventType uint8
	Pad       [3]uint8
}

type lsm_mountPolicyValue struct {
	Action   uint8
	Audit    uint8
	Pad      uint16
	HitCount uint32
}

// loadLsm_mount returns the embedded CollectionSpec for lsm_mount.
func loadLsm_mount() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Lsm_mountBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load lsm_mount: %w", err)
	}

	return spec, err
}

// loadLsm_mountObjects loads lsm_mount and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*lsm_mountObjects
//	*lsm_mountPrograms
//	*lsm_mountMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadLsm_mountObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadLsm_mount()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// lsm_mountSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsm_mountSpecs struct {
	lsm_mountProgramSpecs
	lsm_mountMapSpecs
	lsm_mountVariableSpecs
}

// lsm_mountProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsm_mountProgramSpecs struct {
	LsmMountCheck *ebpf.ProgramSpec `ebpf:"lsm_mount_check"`
}

// lsm_mountMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsm_mountMapSpecs struct {
	LsmCgroupFilter *ebpf.MapSpec `ebpf:"lsm_cgroup_filter"`
	LsmEnforce      *ebpf.MapSpec `ebpf:"lsm_enforce"`
	LsmEvents       *ebpf.MapSpec `ebpf:"lsm_events"`
	PolicyMap       *ebpf.MapSpec `ebpf:"policy_map"`
}

// lsm_mountVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsm_mountVariableSpecs struct {
	UnusedPolicyKey   *ebpf.VariableSpec `ebpf:"unused_policy_key"`
	UnusedPolicyValue *ebpf.VariableSpec `ebpf:"unused_policy_value"`
	UnusedWarmorEvent *ebpf.VariableSpec `ebpf:"unused_warmor_event"`
}

// lsm_mountObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadLsm_mountObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsm_mountObjects struct {
	lsm_mountPrograms
	lsm_mountMaps
	lsm_mountVariables
}

func (o *lsm_mountObjects) Close() error {
	return _Lsm_mountClose(
		&o.lsm_mountPrograms,
		&o.lsm_mountMaps,
	)
}

// lsm_mountMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadLsm_mountObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsm_mountMaps struct {
	LsmCgroupFilter *ebpf.Map `ebpf:"lsm_cgroup_filter"`
	LsmEnforce      *ebpf.Map `ebpf:"lsm_enforce"`
	LsmEvents       *ebpf.Map `ebpf:"lsm_events"`
	PolicyMap       *ebpf.Map `ebpf:"policy_map"`
}

func (m *lsm_mountMaps) Close() error {
	return _Lsm_mountClose(
		m.LsmCgroupFilter,
		m.LsmEnforce,
		m.LsmEvents,
		m.PolicyMap,
	)
}

// lsm_mountVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadLsm_mountObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsm_mountVariables struct {
	UnusedPolicyKey   *ebpf.Variable `ebpf:"unused_policy_key"`
	UnusedPolicyValue *ebpf.Variable `ebpf:"unused_policy_value"`
	UnusedWarmorEvent *ebpf.Variable `ebpf:"unused_warmor_event"`
}

// lsm_mountPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadLsm_mountObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsm_mountPrograms struct {
	LsmMountCheck *ebpf.Program `ebpf:"lsm_mount_check"`
}

func (p *lsm_mountPrograms) Close() error {
	return _Lsm_mountClose(
		p.LsmMountCheck,
	)
}

func _Lsm_mountClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed lsm_mount_bpfeb.o
var _Lsm_mountBytes []byte
