// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type lsm_execPolicyKey struct {
	CgroupId  uint64
	RuleHash  uint32
	EventType uint8
	Pad       [3]uint8
}

type lsm_execPolicyValue struct {
	Action   uint8
	Audit    uint8
	Pad      uint16
	HitCount uint32
}

type lsm_execWarmorEvent struct {
	Pid          uint32
	Uid          uint32
	Gid          uint32
	Comm         [16]int8
	Filename     [256]int8
	_            [4]byte
	Timestamp    uint64
	CgroupId     uint64
	EventType    uint8
	Decision     uint8
	RemotePort   uint16
	RemoteAddrV4 uint32
	RemoteAddrV6 [16]uint8
}

// loadLsm_exec returns the embedded CollectionSpec for lsm_exec.
func loadLsm_exec() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Lsm_execBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load lsm_exec: %w", err)
	}

	return spec, err
}

// loadLsm_execObjects loads lsm_exec and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*lsm_execObjects
//	*lsm_execPrograms
//	*lsm_execMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadLsm_execObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadLsm_exec()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// lsm_execSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsm_execSpecs struct {
	lsm_execProgramSpecs
	lsm_execMapSpecs
	lsm_execVariableSpecs
}

// lsm_execProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsm_execProgramSpecs struct {
	LsmExecCheck *ebpf.ProgramSpec `ebpf:"lsm_exec_check"`
}

// lsm_execMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsm_execMapSpecs struct {
	LsmCgroupFilter *ebpf.MapSpec `ebpf:"lsm_cgroup_filter"`
	LsmEnforce      *ebpf.MapSpec `ebpf:"lsm_enforce"`
	LsmEvents       *ebpf.MapSpec `ebpf:"lsm_events"`
	PolicyMap       *ebpf.MapSpec `ebpf:"policy_map"`
}

// lsm_execVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsm_execVariableSpecs struct {
	UnusedPolicyKey   *ebpf.VariableSpec `ebpf:"unused_policy_key"`
	UnusedPolicyValue *ebpf.VariableSpec `ebpf:"unused_policy_value"`
	UnusedWarmorEvent *ebpf.VariableSpec `ebpf:"unused_warmor_event"`
}

// lsm_execObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadLsm_execObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsm_execObjects struct {
	lsm_execPrograms
	lsm_execMaps
	lsm_execVariables
}

func (o *lsm_execObjects) Close() error {
	return _Lsm_execClose(
		&o.lsm_execPrograms,
		&o.lsm_execMaps,
	)
}

// lsm_execMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadLsm_execObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsm_execMaps struct {
	LsmCgroupFilter *ebpf.Map `ebpf:"lsm_cgroup_filter"`
	LsmEnforce      *ebpf.Map `ebpf:"lsm_enforce"`
	LsmEvents       *ebpf.Map `ebpf:"lsm_events"`
	PolicyMap       *ebpf.Map `ebpf:"policy_map"`
}

func (m *lsm_execMaps) Close() error {
	return _Lsm_execClose(
		m.LsmCgroupFilter,
		m.LsmEnforce,
		m.LsmEvents,
		m.PolicyMap,
	)
}

// lsm_execVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadLsm_execObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsm_execVariables struct {
	UnusedPolicyKey   *ebpf.Variable `ebpf:"unused_policy_key"`
	UnusedPolicyValue *ebpf.Variable `ebpf:"unused_policy_value"`
	UnusedWarmorEvent *ebpf.Variable `ebpf:"unused_warmor_event"`
}

// lsm_execPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadLsm_execObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsm_execPrograms struct {
	LsmExecCheck *ebpf.Program `ebpf:"lsm_exec_check"`
}

func (p *lsm_execPrograms) Close() error {
	return _Lsm_execClose(
		p.LsmExecCheck,
	)
}

func _Lsm_execClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed lsm_exec_bpfeb.o
var _Lsm_execBytes []byte
