// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type lsm_filePolicyKey struct {
	CgroupId  uint64
	RuleHash  uint32
	EventType uint8
	Pad       [3]uint8
}

type lsm_filePolicyValue struct {
	Action   uint8
	Audit    uint8
	Pad      uint16
	HitCount uint32
}

type lsm_fileWarmorEvent struct {
	Pid          uint32
	Uid          uint32
	Gid          uint32
	Comm         [16]int8
	Filename     [256]int8
	_            [4]byte
	Timestamp    uint64
	CgroupId     uint64
	EventType    uint8
	Decision     uint8
	RemotePort   uint16
	RemoteAddrV4 uint32
	RemoteAddrV6 [16]uint8
}

// loadLsm_file returns the embedded CollectionSpec for lsm_file.
func loadLsm_file() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Lsm_fileBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load lsm_file: %w", err)
	}

	return spec, err
}

// loadLsm_fileObjects loads lsm_file and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*lsm_fileObjects
//	*lsm_filePrograms
//	*lsm_fileMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadLsm_fileObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadLsm_file()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// lsm_fileSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsm_fileSpecs struct {
	lsm_fileProgramSpecs
	lsm_fileMapSpecs
	lsm_fileVariableSpecs
}

// lsm_fileProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsm_fileProgramSpecs struct {
	LsmFileCheck *ebpf.ProgramSpec `ebpf:"lsm_file_check"`
}

// lsm_fileMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsm_fileMapSpecs struct {
	LsmCgroupFilter *ebpf.MapSpec `ebpf:"lsm_cgroup_filter"`
	LsmEnforce      *ebpf.MapSpec `ebpf:"lsm_enforce"`
	LsmEvents       *ebpf.MapSpec `ebpf:"lsm_events"`
	PolicyMap       *ebpf.MapSpec `ebpf:"policy_map"`
}

// lsm_fileVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsm_fileVariableSpecs struct {
	UnusedPolicyKey   *ebpf.VariableSpec `ebpf:"unused_policy_key"`
	UnusedPolicyValue *ebpf.VariableSpec `ebpf:"unused_policy_value"`
	UnusedWarmorEvent *ebpf.VariableSpec `ebpf:"unused_warmor_event"`
}

// lsm_fileObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadLsm_fileObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsm_fileObjects struct {
	lsm_filePrograms
	lsm_fileMaps
	lsm_fileVariables
}

func (o *lsm_fileObjects) Close() error {
	return _Lsm_fileClose(
		&o.lsm_filePrograms,
		&o.lsm_fileMaps,
	)
}

// lsm_fileMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadLsm_fileObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsm_fileMaps struct {
	LsmCgroupFilter *ebpf.Map `ebpf:"lsm_cgroup_filter"`
	LsmEnforce      *ebpf.Map `ebpf:"lsm_enforce"`
	LsmEvents       *ebpf.Map `ebpf:"lsm_events"`
	PolicyMap       *ebpf.Map `ebpf:"policy_map"`
}

func (m *lsm_fileMaps) Close() error {
	return _Lsm_fileClose(
		m.LsmCgroupFilter,
		m.LsmEnforce,
		m.LsmEvents,
		m.PolicyMap,
	)
}

// lsm_fileVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadLsm_fileObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsm_fileVariables struct {
	UnusedPolicyKey   *ebpf.Variable `ebpf:"unused_policy_key"`
	UnusedPolicyValue *ebpf.Variable `ebpf:"unused_policy_value"`
	UnusedWarmorEvent *ebpf.Variable `ebpf:"unused_warmor_event"`
}

// lsm_filePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadLsm_fileObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsm_filePrograms struct {
	LsmFileCheck *ebpf.Program `ebpf:"lsm_file_check"`
}

func (p *lsm_filePrograms) Close() error {
	return _Lsm_fileClose(
		p.LsmFileCheck,
	)
}

func _Lsm_fileClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed lsm_file_bpfel.o
var _Lsm_fileBytes []byte
