// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type lsm_connectPolicyKey struct {
	CgroupId  uint64
	RuleHash  uint32
	EventType uint8
	Pad       [3]uint8
}

type lsm_connectPolicyValue struct {
	Action   uint8
	Audit    uint8
	Pad      uint16
	HitCount uint32
}

// loadLsm_connect returns the embedded CollectionSpec for lsm_connect.
func loadLsm_connect() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Lsm_connectBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load lsm_connect: %w", err)
	}

	return spec, err
}

// loadLsm_connectObjects loads lsm_connect and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*lsm_connectObjects
//	*lsm_connectPrograms
//	*lsm_connectMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadLsm_connectObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadLsm_connect()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// lsm_connectSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsm_connectSpecs struct {
	lsm_connectProgramSpecs
	lsm_connectMapSpecs
	lsm_connectVariableSpecs
}

// lsm_connectProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsm_connectProgramSpecs struct {
	LsmConnectCheck *ebpf.ProgramSpec `ebpf:"lsm_connect_check"`
}

// lsm_connectMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsm_connectMapSpecs struct {
	LsmCgroupFilter *ebpf.MapSpec `ebpf:"lsm_cgroup_filter"`
	LsmEnforce      *ebpf.MapSpec `ebpf:"lsm_enforce"`
	LsmEvents       *ebpf.MapSpec `ebpf:"lsm_events"`
	PolicyMap       *ebpf.MapSpec `ebpf:"policy_map"`
}

// lsm_connectVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsm_connectVariableSpecs struct {
	UnusedPolicyKey   *ebpf.VariableSpec `ebpf:"unused_policy_key"`
	UnusedPolicyValue *ebpf.VariableSpec `ebpf:"unused_policy_value"`
	UnusedWarmorEvent *ebpf.VariableSpec `ebpf:"unused_warmor_event"`
}

// lsm_connectObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadLsm_connectObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsm_connectObjects struct {
	lsm_connectPrograms
	lsm_connectMaps
	lsm_connectVariables
}

func (o *lsm_connectObjects) Close() error {
	return _Lsm_connectClose(
		&o.lsm_connectPrograms,
		&o.lsm_connectMaps,
	)
}

// lsm_connectMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadLsm_connectObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsm_connectMaps struct {
	LsmCgroupFilter *ebpf.Map `ebpf:"lsm_cgroup_filter"`
	LsmEnforce      *ebpf.Map `ebpf:"lsm_enforce"`
	LsmEvents       *ebpf.Map `ebpf:"lsm_events"`
	PolicyMap       *ebpf.Map `ebpf:"policy_map"`
}

func (m *lsm_connectMaps) Close() error {
	return _Lsm_connectClose(
		m.LsmCgroupFilter,
		m.LsmEnforce,
		m.LsmEvents,
		m.PolicyMap,
	)
}

// lsm_connectVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadLsm_connectObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsm_connectVariables struct {
	UnusedPolicyKey   *ebpf.Variable `ebpf:"unused_policy_key"`
	UnusedPolicyValue *ebpf.Variable `ebpf:"unused_policy_value"`
	UnusedWarmorEvent *ebpf.Variable `ebpf:"unused_warmor_event"`
}

// lsm_connectPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadLsm_connectObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsm_connectPrograms struct {
	LsmConnectCheck *ebpf.Program `ebpf:"lsm_connect_check"`
}

func (p *lsm_connectPrograms) Close() error {
	return _Lsm_connectClose(
		p.LsmConnectCheck,
	)
}

func _Lsm_connectClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed lsm_connect_bpfeb.o
var _Lsm_connectBytes []byte
