// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type lsm_bindPolicyKey struct {
	CgroupId  uint64
	RuleHash  uint32
	EventType uint8
	Pad       [3]uint8
}

type lsm_bindPolicyValue struct {
	Action   uint8
	Audit    uint8
	Pad      uint16
	HitCount uint32
}

// loadLsm_bind returns the embedded CollectionSpec for lsm_bind.
func loadLsm_bind() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Lsm_bindBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load lsm_bind: %w", err)
	}

	return spec, err
}

// loadLsm_bindObjects loads lsm_bind and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*lsm_bindObjects
//	*lsm_bindPrograms
//	*lsm_bindMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadLsm_bindObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadLsm_bind()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// lsm_bindSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsm_bindSpecs struct {
	lsm_bindProgramSpecs
	lsm_bindMapSpecs
	lsm_bindVariableSpecs
}

// lsm_bindProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsm_bindProgramSpecs struct {
	LsmBindCheck *ebpf.ProgramSpec `ebpf:"lsm_bind_check"`
}

// lsm_bindMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsm_bindMapSpecs struct {
	LsmCgroupFilter *ebpf.MapSpec `ebpf:"lsm_cgroup_filter"`
	LsmEnforce      *ebpf.MapSpec `ebpf:"lsm_enforce"`
	LsmEvents       *ebpf.MapSpec `ebpf:"lsm_events"`
	PolicyMap       *ebpf.MapSpec `ebpf:"policy_map"`
}

// lsm_bindVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsm_bindVariableSpecs struct {
	UnusedPolicyKey   *ebpf.VariableSpec `ebpf:"unused_policy_key"`
	UnusedPolicyValue *ebpf.VariableSpec `ebpf:"unused_policy_value"`
	UnusedWarmorEvent *ebpf.VariableSpec `ebpf:"unused_warmor_event"`
}

// lsm_bindObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadLsm_bindObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsm_bindObjects struct {
	lsm_bindPrograms
	lsm_bindMaps
	lsm_bindVariables
}

func (o *lsm_bindObjects) Close() error {
	return _Lsm_bindClose(
		&o.lsm_bindPrograms,
		&o.lsm_bindMaps,
	)
}

// lsm_bindMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadLsm_bindObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsm_bindMaps struct {
	LsmCgroupFilter *ebpf.Map `ebpf:"lsm_cgroup_filter"`
	LsmEnforce      *ebpf.Map `ebpf:"lsm_enforce"`
	LsmEvents       *ebpf.Map `ebpf:"lsm_events"`
	PolicyMap       *ebpf.Map `ebpf:"policy_map"`
}

func (m *lsm_bindMaps) Close() error {
	return _Lsm_bindClose(
		m.LsmCgroupFilter,
		m.LsmEnforce,
		m.LsmEvents,
		m.PolicyMap,
	)
}

// lsm_bindVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadLsm_bindObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsm_bindVariables struct {
	UnusedPolicyKey   *ebpf.Variable `ebpf:"unused_policy_key"`
	UnusedPolicyValue *ebpf.Variable `ebpf:"unused_policy_value"`
	UnusedWarmorEvent *ebpf.Variable `ebpf:"unused_warmor_event"`
}

// lsm_bindPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadLsm_bindObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsm_bindPrograms struct {
	LsmBindCheck *ebpf.Program `ebpf:"lsm_bind_check"`
}

func (p *lsm_bindPrograms) Close() error {
	return _Lsm_bindClose(
		p.LsmBindCheck,
	)
}

func _Lsm_bindClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed lsm_bind_bpfeb.o
var _Lsm_bindBytes []byte
