// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type openat_monitorFileEvent struct {
	Pid       uint32
	Uid       uint32
	Gid       uint32
	Comm      [16]int8
	Path      [256]int8
	Flags     uint32
	Mode      uint32
	_         [4]byte
	Timestamp uint64
	CgroupId  uint64
}

// loadOpenat_monitor returns the embedded CollectionSpec for openat_monitor.
func loadOpenat_monitor() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Openat_monitorBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load openat_monitor: %w", err)
	}

	return spec, err
}

// loadOpenat_monitorObjects loads openat_monitor and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*openat_monitorObjects
//	*openat_monitorPrograms
//	*openat_monitorMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadOpenat_monitorObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadOpenat_monitor()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// openat_monitorSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type openat_monitorSpecs struct {
	openat_monitorProgramSpecs
	openat_monitorMapSpecs
	openat_monitorVariableSpecs
}

// openat_monitorProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type openat_monitorProgramSpecs struct {
	TracepointSyscallsSysEnterOpenat *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_openat"`
}

// openat_monitorMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type openat_monitorMapSpecs struct {
	CgroupFilter *ebpf.MapSpec `ebpf:"cgroup_filter"`
	FileEvents   *ebpf.MapSpec `ebpf:"file_events"`
}

// openat_monitorVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type openat_monitorVariableSpecs struct {
	UnusedFileEvent *ebpf.VariableSpec `ebpf:"unused_file_event"`
}

// openat_monitorObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadOpenat_monitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type openat_monitorObjects struct {
	openat_monitorPrograms
	openat_monitorMaps
	openat_monitorVariables
}

func (o *openat_monitorObjects) Close() error {
	return _Openat_monitorClose(
		&o.openat_monitorPrograms,
		&o.openat_monitorMaps,
	)
}

// openat_monitorMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadOpenat_monitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type openat_monitorMaps struct {
	CgroupFilter *ebpf.Map `ebpf:"cgroup_filter"`
	FileEvents   *ebpf.Map `ebpf:"file_events"`
}

func (m *openat_monitorMaps) Close() error {
	return _Openat_monitorClose(
		m.CgroupFilter,
		m.FileEvents,
	)
}

// openat_monitorVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadOpenat_monitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type openat_monitorVariables struct {
	UnusedFileEvent *ebpf.Variable `ebpf:"unused_file_event"`
}

// openat_monitorPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadOpenat_monitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type openat_monitorPrograms struct {
	TracepointSyscallsSysEnterOpenat *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_openat"`
}

func (p *openat_monitorPrograms) Close() error {
	return _Openat_monitorClose(
		p.TracepointSyscallsSysEnterOpenat,
	)
}

func _Openat_monitorClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed openat_monitor_bpfeb.o
var _Openat_monitorBytes []byte
