apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "warmor.fullname" . }}
  labels:
    {{- include "warmor.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
  - apiGroups: ["warmor.io"]
    resources: ["warmorpolicies"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["warmor.io"]
    resources: ["warmorpolicies/status"]
    verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "warmor.fullname" . }}
  labels:
    {{- include "warmor.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "warmor.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "warmor.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
