apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "warmor.fullname" . }}-policy
  labels:
    {{- include "warmor.labels" . | nindent 4 }}
data:
  policy.yaml: |
    {{- .Values.policy.yaml | nindent 4 }}
