{{- if and .Values.priorityClass.enabled (not .Values.priorityClass.name) }}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ include "warmor.fullname" . }}
  labels:
    {{- include "warmor.labels" . | nindent 4 }}
globalDefault: false
value: {{ .Values.priorityClass.value }}
preemptionPolicy: PreemptLowerPriority
description: "Critical security daemon - must not be evicted"
{{- end }}
