{{- if .Values.webhook.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "warmor.fullname" . }}
  labels:
    {{- include "warmor.labels" . | nindent 4 }}
  {{- if .Values.webhook.certManager.enabled }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "warmor.fullname" . }}-webhook
  {{- end }}
webhooks:
  - name: policy.warmor.io
    admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ include "warmor.fullname" . }}-webhook
        namespace: {{ .Release.Namespace }}
        path: /validate-warmorpolicy
        port: {{ .Values.webhook.port }}
      {{- if and (not .Values.webhook.certManager.enabled) .Values.webhook.caBundle }}
      caBundle: {{ .Values.webhook.caBundle }}
      {{- end }}
    failurePolicy: Fail
    matchPolicy: Equivalent
    rules:
      - apiGroups:
          - warmor.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - warmorpolicies
        scope: Namespaced
    sideEffects: None
    timeoutSeconds: 10
{{- end }}
